/*
 * This file was generated automatically by ExtUtils::ParseXS version 2.2210 from the
 * contents of Faidx.xs. Do not edit this file, edit Faidx.xs instead.
 *
 *	ANY CHANGES MADE HERE WILL BE LOST! 
 *
 */

#line 1 "Faidx.xs"
#include "EXTERN.h"
#include "perl.h"
#include "XSUB.h"

#include "ppport.h"

#include <stdio.h>

#include "htslib/faidx.h"
#ifndef Newx
#  define Newx(v,n,t) New(0,v,n,t)
#endif


void print_hello()
{
  printf( "Hello World from the Faidx XS module\n" ) ;
}

// Code is written to use a blessed int pointer to this strut as an object
// You cannot use Data::Dumper to inspect the Faidx object. Sorry
typedef struct 
{
  char* path;
  faidx_t* index;
} Faidx ;


SV* new(const char * classname, const char * path) 
{
  Faidx   * faidx;
  SV      * obj;
  SV      * obj_ref;
  faidx_t * fai;
  
  Newx(faidx, 1, Faidx);
  
  fai = fai_load(path);
  faidx->path = savepv(path);
  faidx->index = fai;
  printf( "Making New Object\n" ) ;
  obj = newSViv((IV)faidx);
  obj_ref = newRV_noinc(obj);
  printf( "obj address %p\n", &obj ) ;
  sv_bless(obj_ref, gv_stashpv(classname, GV_ADD));
  SvREADONLY_on(obj);

  return obj_ref;
}


void get_sequence(SV* obj, SV* location, SV** seq, int* seq_len) 
{
  faidx_t *fai;
  char* char_seq;
  
  *seq = newSVpvn("",0);
  *seq_len = 0;
  
  fai = ((Faidx*)SvIV(SvRV(obj)))->index;
  //Fetch sequence
  printf( "\tget_sequence:Going to fetch sequence\n" ) ;
  /* char *fai_fetch(const faidx_t *fai, const char *reg, int *len); */
  char_seq = fai_fetch(fai, SvPV(location, PL_na), seq_len);
  printf( "\tget_sequence: Sequence obtained in XS function is:%s\n", char_seq ) ;

  //Push into a SV
  sv_catpv(*seq, char_seq);
  //Free the buffer created by faidx
  free(char_seq);
}


int has_sequence(SV* obj, SV* location) 
{
  printf( "has_sequence called\n" ) ;
  printf( "\tobj address %p\n", &obj ) ;

  int has_seq=-1 ;
  printf( "\tfor location:%s\n",SvPV(location, PL_na) ) ;
  printf( "\thas_seq:%d\n", has_seq ) ;
  has_seq = faidx_has_seq(((Faidx*)SvIV(SvRV(obj)))->index, SvPV(location, PL_na));
  printf( "\thas_seq:%d\n", has_seq ) ;
  return has_seq;
}

int length(SV* obj, char* identifier)
{
    printf( "length() called\n" ) ;
    printf( "\tobj address %p\n", &obj ) ;
    int length = 22456 ;
    faidx_t *fai = ((Faidx*)SvIV(SvRV(obj)))->index ;
    
    /* int faidx_seq_len(const faidx_t *fai, const char *seq);*/
    length = faidx_seq_len(fai, identifier) ;
    return length ;
}

void DESTROY(SV* obj) 
{
  printf( "DESTROY called\n" ) ;
  printf( "\tGoodbye, object with address %p\n", &obj ) ;

  Faidx* faidx = (Faidx*)SvIV(SvRV(obj));
  Safefree(faidx->path);
  fai_destroy(faidx->index);
  Safefree(faidx);
}


#line 121 "Faidx.c"
#ifndef PERL_UNUSED_VAR
#  define PERL_UNUSED_VAR(var) if (0) var = var
#endif

#ifndef PERL_ARGS_ASSERT_CROAK_XS_USAGE
#define PERL_ARGS_ASSERT_CROAK_XS_USAGE assert(cv); assert(params)

/* prototype to pass -Wmissing-prototypes */
STATIC void
S_croak_xs_usage(pTHX_ const CV *const cv, const char *const params);

STATIC void
S_croak_xs_usage(pTHX_ const CV *const cv, const char *const params)
{
    const GV *const gv = CvGV(cv);

    PERL_ARGS_ASSERT_CROAK_XS_USAGE;

    if (gv) {
        const char *const gvname = GvNAME(gv);
        const HV *const stash = GvSTASH(gv);
        const char *const hvname = stash ? HvNAME(stash) : NULL;

        if (hvname)
            Perl_croak(aTHX_ "Usage: %s::%s(%s)", hvname, gvname, params);
        else
            Perl_croak(aTHX_ "Usage: %s(%s)", gvname, params);
    } else {
        /* Pants. I don't think that it should be possible to get here. */
        Perl_croak(aTHX_ "Usage: CODE(0x%"UVxf")(%s)", PTR2UV(cv), params);
    }
}
#undef  PERL_ARGS_ASSERT_CROAK_XS_USAGE

#ifdef PERL_IMPLICIT_CONTEXT
#define croak_xs_usage(a,b)	S_croak_xs_usage(aTHX_ a,b)
#else
#define croak_xs_usage		S_croak_xs_usage
#endif

#endif

/* NOTE: the prototype of newXSproto() is different in versions of perls,
 * so we define a portable version of newXSproto()
 */
#ifdef newXS_flags
#define newXSproto_portable(name, c_impl, file, proto) newXS_flags(name, c_impl, file, proto, 0)
#else
#define newXSproto_portable(name, c_impl, file, proto) (PL_Sv=(SV*)newXS(name, c_impl, file), sv_setpv(PL_Sv, proto), (CV*)PL_Sv)
#endif /* !defined(newXS_flags) */

#line 173 "Faidx.c"

XS(XS_Faidx_print_hello); /* prototype to pass -Wmissing-prototypes */
XS(XS_Faidx_print_hello)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 0)
       croak_xs_usage(cv,  "");
    {

	print_hello();
    }
    XSRETURN_EMPTY;
}


XS(XS_Faidx_new); /* prototype to pass -Wmissing-prototypes */
XS(XS_Faidx_new)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 2)
       croak_xs_usage(cv,  "classname, path");
    {
	char*	classname = (char *)SvPV_nolen(ST(0));
	char*	path = (char *)SvPV_nolen(ST(1));
	SV *	RETVAL;

	RETVAL = new(classname, path);
	ST(0) = RETVAL;
	sv_2mortal(ST(0));
    }
    XSRETURN(1);
}


XS(XS_Faidx_get_sequence); /* prototype to pass -Wmissing-prototypes */
XS(XS_Faidx_get_sequence)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 2)
       croak_xs_usage(cv,  "obj, location");
    {
	SV*	obj = ST(0);
	SV*	location = ST(1);
	SV*	seq;
	int	length;

	get_sequence(obj, location, &seq, &length);
	XSprePUSH;	EXTEND(SP,2);
	PUSHs(sv_newmortal());
	ST(0) = seq;
	PUSHs(sv_newmortal());
	sv_setiv(ST(1), (IV)length);
    }
    XSRETURN(2);
}


XS(XS_Faidx_has_sequence); /* prototype to pass -Wmissing-prototypes */
XS(XS_Faidx_has_sequence)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 2)
       croak_xs_usage(cv,  "obj, location");
    {
	SV*	obj = ST(0);
	SV*	location = ST(1);
	int	RETVAL;
	dXSTARG;

	RETVAL = has_sequence(obj, location);
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}


XS(XS_Faidx_DESTROY); /* prototype to pass -Wmissing-prototypes */
XS(XS_Faidx_DESTROY)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 1)
       croak_xs_usage(cv,  "obj");
    {
	SV*	obj = ST(0);

	DESTROY(obj);
    }
    XSRETURN_EMPTY;
}


XS(XS_Faidx_length); /* prototype to pass -Wmissing-prototypes */
XS(XS_Faidx_length)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 2)
       croak_xs_usage(cv,  "obj, seq_id");
    {
	SV*	obj = ST(0);
	char*	seq_id = (char *)SvPV_nolen(ST(1));
	int	RETVAL;
	dXSTARG;

	RETVAL = length(obj, seq_id);
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}

#ifdef __cplusplus
extern "C"
#endif
XS(boot_Faidx); /* prototype to pass -Wmissing-prototypes */
XS(boot_Faidx)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
#if (PERL_REVISION == 5 && PERL_VERSION < 9)
    char* file = __FILE__;
#else
    const char* file = __FILE__;
#endif

    PERL_UNUSED_VAR(cv); /* -W */
    PERL_UNUSED_VAR(items); /* -W */
#ifdef XS_APIVERSION_BOOTCHECK
    XS_APIVERSION_BOOTCHECK;
#endif
    XS_VERSION_BOOTCHECK ;

        newXS("Faidx::print_hello", XS_Faidx_print_hello, file);
        newXS("Faidx::new", XS_Faidx_new, file);
        newXS("Faidx::get_sequence", XS_Faidx_get_sequence, file);
        newXS("Faidx::has_sequence", XS_Faidx_has_sequence, file);
        newXS("Faidx::DESTROY", XS_Faidx_DESTROY, file);
        newXS("Faidx::length", XS_Faidx_length, file);
#if (PERL_REVISION == 5 && PERL_VERSION >= 9)
  if (PL_unitcheckav)
       call_list(PL_scopestack_ix, PL_unitcheckav);
#endif
    XSRETURN_YES;
}

